name: Setup
description: "Setup Node.js"

inputs:
  registry:
    description: "The registry URL to use"
    required: false

runs:
  using: "composite"
  steps:
    - name: corepack enable
      shell: bash
      run: corepack enable
    - name: Use Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: .node-version
        cache: "pnpm"
        registry-url: ${{ inputs.registry }}
    - name: Install dependencies
      shell: bash
      run: pnpm install
