name: Setup
description: "Setup Node.js"

inputs:
  registry:
    description: "The registry URL to use"
    required: false

runs:
  using: "composite"
  steps:
    - name: corepack enable
      shell: bash
      run: corepack enable
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: "pnpm"
        registry-url: ${{ inputs.registry }}
    - name: Install dependencies
      shell: bash
      run: pnpm install
